[tox]
envlist = py39-wagtail42-crx2, py39-wagtail42-crx2-float, py310-wagtail52-crx3, py310-wagtail52-crx3-float, py311-wagtail63-crx4, py311-wagtail63-crx4-float, py311-wagtail63-crx5, py311-wagtail63-crx5-float
isolated_build = true

[testenv]
package = editable
deps =
    -r requirements.txt
    -c constraints/{envname}.txt
    pytest>=7.4
    pytest-django>=4.8
commands = pytest
setenv =
    DJANGO_SETTINGS_MODULE = testapp.settings.test
